### ISSUE TITLE
Timeout in some chimp test

### ISSUE THREAD

**Issue by vjrj** [DemocracyEarth/sovereign#267]
Sometimes, we have a timeout running tests:
```
     Error: asynchronous script timeout: result was not received in 5 seconds
         at Object.clientLogin (features/step_definitions/support/fixtures/user-fixtures.js:36:35)
```
most of the times the test doesn't fails.

@domi41 can we increase this browser timeout without problems?

**Comment by domi41** [comment]
The async timeout is safe to augment, as it's not a sleep and if the login happens sooner, it will not wait for the full duration. Let's try with 15s !

---

OOOOOPS.

Sorry I meant to make a PR, and instead I pushed straight to master ! :scream:

**Comment by vjrj** [comment]
Grrrrrrrrr, still fails:

https://ci.comunes.org/job/sovereign/39/console

**Comment by vjrj** [comment]
I see in the console this error:

```Expected to find a document to change

    /packages/mongo.js in Object.update at line 308:27
    /packages/ddp-client.js in Object.store.(anonymous function) [as update] at line 632:41
(...)
```

so seems that fails in `transaction.js` for some reason.

**Comment by vjrj** [comment]
Ok, now I see that some error arise on `collective.js:onCreated` call to userCount:

```
I20180417-17:41:30.195(2)? { publish: 'contractDrafts', user: 'richards', insert: false }
I20180417-17:41:30.603(2)? Exception while invoking method 'userCount' { stack: 'TypeError: Cannot read property \'username\' of undefined\n    at MethodInvocation.userCount (imports/api/server/methods.js:78:52)\n    at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)\n    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Promise (packages/ddp-server/livedata_server.js:715:46)\n    at new Promise (<anonymous>)\n    at Session.method (packages/ddp-server/livedata_server.js:689:23)\n    at packages/mdg_meteor-apm-agent.js:2617:38\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)\n    at packages/ddp-server/livedata_server.js:559:43',
I20180417-17:41:30.604(2)?   source: 'method' }
```
https://ci.comunes.org/job/sovereign/72/console
